# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  

from typing import List, Dict  

from swagger_server.models.base_model_ import Model
from swagger_server import util


class POIGeocode(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, latitude: str=None, longitude: str=None):  # noqa: E501
        """POIGeocode - a model defined in Swagger

        :param latitude: The latitude of this POIGeocode.  # noqa: E501
        :type latitude: str
        :param longitude: The longitude of this POIGeocode.  # noqa: E501
        :type longitude: str
        """
        self.swagger_types = {
            'latitude': str,
            'longitude': str
        }

        self.attribute_map = {
            'latitude': 'latitude',
            'longitude': 'longitude'
        }

        self._latitude = latitude
        self._longitude = longitude

    @classmethod
    def from_dict(cls, dikt) -> 'POIGeocode':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The POI_geocode of this POIGeocode.  # noqa: E501
        :rtype: POIGeocode
        """
        return util.deserialize_model(dikt, cls)

    @property
    def latitude(self) -> str:
        """Gets the latitude of this POIGeocode.

        geocoded latitude of POI  # noqa: E501

        :return: The latitude of this POIGeocode.
        :rtype: str
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude: str):
        """Sets the latitude of this POIGeocode.

        geocoded latitude of POI  # noqa: E501

        :param latitude: The latitude of this POIGeocode.
        :type latitude: str
        """

        self._latitude = latitude

    @property
    def longitude(self) -> str:
        """Gets the longitude of this POIGeocode.

        geocoded longitude of POI  # noqa: E501

        :return: The longitude of this POIGeocode.
        :rtype: str
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude: str):
        """Sets the longitude of this POIGeocode.

        geocoded longitude of POI  # noqa: E501

        :param longitude: The longitude of this POIGeocode.
        :type longitude: str
        """

        self._longitude = longitude
